[package]
name = "nexofs-api-governor"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexofs-domain.workspace = true
nexofs-provider-api.workspace = true
tokio = { workspace = true, features = ["sync", "time"] }
rand = "0.8"
tracing.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt", "time", "test-util"] }

