[package]
name = "nexofs-content-cache"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
nexofs-domain.workspace = true
nexofs-provider-api.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
thiserror.workspace = true
tracing.workspace = true
reflink-copy = "0.1"
nix = { version = "0.26", default-features = false, features = ["fs"] }
libc = "0.2"

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tempfile = "3"
